# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables (optional)
ENV POSTGRES_USER=dheeraj
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_DB=apparel

# Expose the default PostgreSQL port
EXPOSE 5432
